/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelManagementSystem;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vulcanprime
 */
public class HotelSystem extends javax.swing.JFrame {
public int InvoiceID=0;
    /**
     * Creates new form HotelSystem
     */
    public HotelSystem() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jtxtCustID = new javax.swing.JTextField();
        jtxtLastName = new javax.swing.JTextField();
        jtxtMobile = new javax.swing.JTextField();
        jtxtAdd1 = new javax.swing.JTextField();
        jtxtAdd2 = new javax.swing.JTextField();
        jtxtZipCode = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtRoomNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateBirthdate = new com.toedter.calendar.JDateChooser();
        jDateCheckoutDate = new com.toedter.calendar.JDateChooser();
        jDateCheckinDate = new com.toedter.calendar.JDateChooser();
        jcomGender = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTaxAmt = new javax.swing.JTextField();
        jcomRoomType = new javax.swing.JComboBox<>();
        jButtonExit = new javax.swing.JButton();
        onDelete = new javax.swing.JButton();
        onReset = new javax.swing.JButton();
        onDUpdate = new javax.swing.JButton();
        onTotal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtxtEmpID1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtxtEmpAdd1 = new javax.swing.JTextField();
        jtxtEmpFirstName1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtxtEmpAdd2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtxtEmpLastName1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtxtEmpZipCode1 = new javax.swing.JTextField();
        jcomGender1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jtxtEmpMobile1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jtxtEmpEmail1 = new javax.swing.JTextField();
        jButtonExit1 = new javax.swing.JButton();
        onReset1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jcomboxJobTitle = new javax.swing.JComboBox<>();
        jButtonAddToEmp = new javax.swing.JButton();
        onDelete1 = new javax.swing.JButton();
        onDelete2 = new javax.swing.JButton();
        jlblSalary = new javax.swing.JLabel();
        jtxtEmpSalary = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ZipCode: ");

        jLabel2.setText("Mobile: ");

        jLabel3.setText("Check-In Date:");

        jLabel4.setText("Address Line 1: ");

        jLabel5.setText("Email: ");

        jLabel6.setText("FirstName: ");

        jLabel7.setText("LastName: ");

        jLabel8.setText("Address Line 2: ");

        jLabel9.setText("CustomerID: ");

        jLabel10.setText("Check-Out Date: ");

        jLabel11.setText("Gender:");

        jLabel16.setText("Room Type: ");

        jLabel17.setText("Room Number: ");

        jLabel18.setText("Birthdate: ");

        jtxtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstNameActionPerformed(evt);
            }
        });

        jtxtCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustIDActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerID", "FirstName", "LastName", "Gender", "Mobile", "Check-In Date", "Check-Out Date", "Room Type", "Room Number", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        jcomGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", "Alien from Area 51", "Prefer not to say" }));
        jcomGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomGenderActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Sub-Total:");

        jLabel19.setText("Tax Amount:");

        jLabel14.setText("Total:");

        jtxtTaxAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxAmtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTaxAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTaxAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jcomRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard-Twin Bed", "Executive-Queen Bed", "Suite-King Bed", "Presidential-Gold Bed" }));
        jcomRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomRoomTypeActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        onDelete.setText("Delete");
        onDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDeleteActionPerformed(evt);
            }
        });

        onReset.setText("Clear All");
        onReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onResetActionPerformed(evt);
            }
        });

        onDUpdate.setText("Invoice");
        onDUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDUpdateActionPerformed(evt);
            }
        });

        onTotal.setText("Total");
        onTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcomGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(onTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(onDUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(onReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(onDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcomRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateCheckoutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateCheckinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 32, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jtxtAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateCheckinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jtxtAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateCheckoutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jcomRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jtxtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jcomGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(onTotal)
                        .addGap(1, 1, 1)
                        .addComponent(onDUpdate)
                        .addGap(1, 1, 1)
                        .addComponent(onReset)
                        .addGap(1, 1, 1)
                        .addComponent(onDelete))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanel1);

        jLabel13.setText("Employee ID:");

        jtxtEmpID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmpID1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Address Line 1: ");

        jtxtEmpFirstName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmpFirstName1ActionPerformed(evt);
            }
        });

        jLabel21.setText("FirstName: ");

        jLabel22.setText("LastName: ");

        jLabel23.setText("ZipCode: ");

        jLabel24.setText("Address Line 2: ");

        jcomGender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", "Alien from Area 51", "Prefer not to say" }));
        jcomGender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomGender1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Gender:");

        jLabel26.setText("Mobile: ");

        jtxtEmpMobile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmpMobile1ActionPerformed(evt);
            }
        });

        jLabel27.setText("Email: ");

        jButtonExit1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonExit1.setText("EXIT");
        jButtonExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit1ActionPerformed(evt);
            }
        });

        onReset1.setText("Clear All");
        onReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onReset1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeID", "FirstName", "LastName", "Email", "Mobile", "Job Title", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel32.setText("Job Title:");

        jcomboxJobTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receptionist", "Room Service Manager", "Booking Manager" }));

        jButtonAddToEmp.setText("Add to Table");
        jButtonAddToEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddToEmpActionPerformed(evt);
            }
        });

        onDelete1.setText("Delete");
        onDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDelete1ActionPerformed(evt);
            }
        });

        onDelete2.setText("Delete");
        onDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDelete2ActionPerformed(evt);
            }
        });

        jlblSalary.setText("Employee Salary:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel13)
                    .addComponent(jLabel22)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtEmpID1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEmpLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEmpFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEmpEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtEmpAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtEmpZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtEmpAdd2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(jcomboxJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jcomGender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(onReset1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddToEmp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(onDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jtxtEmpMobile1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jlblSalary)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtEmpSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButtonExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addGap(32, 32, 32))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(464, 464, 464)
                    .addComponent(onDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(472, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtEmpID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jtxtEmpAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmpFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jtxtEmpAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jtxtEmpLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jtxtEmpZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jtxtEmpEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jcomboxJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jcomGender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jtxtEmpMobile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonAddToEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(onDelete2))
                            .addComponent(onReset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblSalary)
                            .addComponent(jtxtEmpSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(297, 297, 297)
                    .addComponent(onDelete1)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Employee", jPanel3);

        jLabel31.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel31.setText("Hotel Invoice List");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "InvoiceID", "CustomerID", "CustomerName", "ContactNumber", "RoomType", "RoomNumber", "TotalAmount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Invoice", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1030, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustIDActionPerformed

    private void jtxtTaxAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxAmtActionPerformed

    private void jcomGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomGenderActionPerformed

    private JFrame frame;
    
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
       frame=new JFrame("Exit");
       if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?","Hotel Management System", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){;
       System.exit(0);
       }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void onDUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDUpdateActionPerformed
     DefaultTableModel custmodel= (DefaultTableModel) jTable1.getModel();
     DefaultTableModel empmodel= (DefaultTableModel) jTable2.getModel();
     DefaultTableModel invmodel= (DefaultTableModel) jTable3.getModel();
    //    String out=" Customer ID: "+model.getValueAt(jTable1.getSelectedRow(),0)+"\n Guest First Name: "+ model.getValueAt(jTable1.getSelectedRow(),1)+ "\n Guest Last Name: "+model.getValueAt(jTable1.getSelectedRow(),2)+"\n Mobile Number: "+model.getValueAt(jTable1.getSelectedRow(),4)+"\n Room Type: "+model.getValueAt(jTable1.getSelectedRow(),7)+"\n Room Number: "+model.getValueAt(jTable1.getSelectedRow(),8)+"\n Total Amount to be Paid: "+model.getValueAt(jTable1.getSelectedRow(),9);
    //    JOptionPane.showMessageDialog(null,out,"Hotel Management System", JOptionPane.INFORMATION_MESSAGE,null);
    
        invmodel.addRow(new Object[]{
            InvoiceID,
            custmodel.getValueAt(jTable1.getSelectedRow(),0),
            custmodel.getValueAt(jTable1.getSelectedRow(),1)+" "+custmodel.getValueAt(jTable1.getSelectedRow(),2),
            custmodel.getValueAt(jTable1.getSelectedRow(),4),
            custmodel.getValueAt(jTable1.getSelectedRow(),5),
            custmodel.getValueAt(jTable1.getSelectedRow(),6),
            custmodel.getValueAt(jTable1.getSelectedRow(),7),
            custmodel.getValueAt(jTable1.getSelectedRow(),8),
            custmodel.getValueAt(jTable1.getSelectedRow(),9),
        });

        InvoiceID++;
    JOptionPane.showConfirmDialog(null,"Invoice Generation Successful","Hotel Management System", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_onDUpdateActionPerformed

    private void onTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTotalActionPerformed
        /*
        Standard-Twin Bed: $45
        Executive-Queen Bed: $60
        Suite-King Bed: $100
        Presidential-Gold Bed: $900
        */
        int standroom=45;
        int executroom=60;
        int suiteroom=100;
        int presiroom=900;

        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date Checkin_Date=null;
        Date Checkout_Date=null;

        try{
            Checkin_Date=format.parse(format.format(jDateCheckinDate.getDate()));
            Checkout_Date=format.parse(format.format(jDateCheckoutDate.getDate()));

        } catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Invaid Dates Entered!","Hotel Management System", JOptionPane.OK_OPTION);
        }

        if((Checkin_Date.getTime() - Checkout_Date.getTime()) >=0){
            JOptionPane.showMessageDialog(null,"Invalid Dates Entered", "Invalid", JOptionPane.OK_OPTION);
        } else {

            long datediff = Checkin_Date.getTime() - Checkout_Date.getTime();
            int datedifference=(int)(datediff /1000/60/60/24);
            datedifference=Math.abs(datedifference);

            if(jcomRoomType.getSelectedItem().equals("Standard-Twin Bed")){
                jtxtTaxAmt.setText(Integer.toString(datedifference*standroom));
                jtxtSubTotal.setText(Integer.toString(datedifference*standroom));

                double taxtemp=Double.parseDouble(jtxtTaxAmt.getText());
                taxtemp=(taxtemp*2)/100;
                String tax=String.format(("$ %.2f"),taxtemp);
                jtxtTaxAmt.setText(tax);

                double subt=Double.parseDouble(jtxtSubTotal.getText());
                String subtotal=String.format(("$ %.2f"),subt);
                jtxtSubTotal.setText(subtotal);

                String total=String.format(("$ %.2f"),taxtemp+subt);
                jtxtTotal.setText(total);

            } else if(jcomRoomType.getSelectedItem().equals("Executive-Queen Bed")){
                jtxtTotal.setText(Integer.toString(datedifference*executroom));
                jtxtTaxAmt.setText(Integer.toString(datedifference*executroom));
                jtxtSubTotal.setText(Integer.toString(datedifference*executroom));

                double taxtemp=Double.parseDouble(jtxtTaxAmt.getText());
                taxtemp=(taxtemp*2)/100;
                String tax=String.format(("$ %.2f"),taxtemp);
                jtxtTaxAmt.setText(tax);

                double subt=Double.parseDouble(jtxtSubTotal.getText());
                String subtotal=String.format(("$ %.2f"),subt);
                jtxtSubTotal.setText(subtotal);

                String total=String.format(("$ %.2f"),taxtemp+subt);
                jtxtTotal.setText(total);

            }else if(jcomRoomType.getSelectedItem().equals("Suite-King Bed")){
                jtxtTotal.setText(Integer.toString(datedifference*suiteroom));
                jtxtSubTotal.setText(Integer.toString(datedifference*suiteroom));
                jtxtTaxAmt.setText(Integer.toString(datedifference*suiteroom));

                double taxtemp=Double.parseDouble(jtxtTaxAmt.getText());
                taxtemp=(taxtemp*2)/100;
                String tax=String.format(("$ %.2f"),taxtemp);
                jtxtTaxAmt.setText(tax);

                double subt=Double.parseDouble(jtxtSubTotal.getText());
                String subtotal=String.format(("$ %.2f"),subt);
                jtxtSubTotal.setText(subtotal);

                String total=String.format(("$ %.2f"),taxtemp+subt);
                jtxtTotal.setText(total);

            }else if(jcomRoomType.getSelectedItem().equals("Presidential-Gold Bed")){
                jtxtTotal.setText(Integer.toString(datedifference*presiroom));
                jtxtSubTotal.setText(Integer.toString(datedifference*presiroom));
                jtxtTaxAmt.setText(Integer.toString(datedifference*presiroom));

                double taxtemp=Double.parseDouble(jtxtTaxAmt.getText());
                taxtemp=(taxtemp*2)/100;
                String tax=String.format(("$ %.2f"),taxtemp);
                jtxtTaxAmt.setText(tax);

                double subt=Double.parseDouble(jtxtSubTotal.getText());
                String subtotal=String.format(("$ %.2f"),subt);
                jtxtSubTotal.setText(subtotal);

                String total=String.format(("$ %.2f"),taxtemp+subt);
                jtxtTotal.setText(total);
            }

            //-------------------BELOW IS THE CODE-BLOCK TO ADD ROW TO TABLE----------------------

            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{
                jtxtCustID.getText(),
                jtxtFirstName.getText(),
                jtxtLastName.getText(),
                jcomGender.getSelectedItem(),
                jtxtMobile.getText(),
                jDateCheckinDate.getDate(),
                jDateCheckoutDate.getDate(),
                jcomRoomType.getSelectedItem(),
                jtxtRoomNo.getText(),
                jtxtTotal.getText(),
            } );
        }
    }//GEN-LAST:event_onTotalActionPerformed

    private void onResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onResetActionPerformed
        jtxtCustID.setText(null);
        jtxtFirstName.setText(null);
        jtxtLastName.setText(null);
        jDateBirthdate.setDate(null);
        jcomGender.setSelectedIndex(-1);
        jtxtMobile.setText(null);
        jtxtAdd1.setText(null);
        jtxtAdd2.setText(null);
        jtxtZipCode.setText(null);
        jtxtEmail.setText(null);
        jDateCheckinDate.setDate(null);
        jDateCheckoutDate.setDate(null);
        jcomRoomType.setSelectedIndex(-1);
        jtxtRoomNo.setText(null);
        jtxtTaxAmt.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTotal.setText(null);
    }//GEN-LAST:event_onResetActionPerformed

    private void onDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDeleteActionPerformed
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No data to delete", "Hotel Management System", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Please select a row to delete", "Hotel Management System", JOptionPane.OK_OPTION);
            }
        } else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_onDeleteActionPerformed

    private void jtxtEmpID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmpID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmpID1ActionPerformed

    private void jcomGender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomGender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomGender1ActionPerformed

    private void jButtonExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit1ActionPerformed
        frame=new JFrame("Exit");
       if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?","Hotel Management System", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){;
       System.exit(0);
       }
    }//GEN-LAST:event_jButtonExit1ActionPerformed

    private void jtxtEmpMobile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmpMobile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmpMobile1ActionPerformed

    private void onReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onReset1ActionPerformed
        // TODO add your handling code here:
        jtxtEmpID1.setText(null);
        jtxtEmpFirstName1.setText(null);
        jtxtEmpLastName1.setText(null);
        jcomGender1.setSelectedIndex(-1);
        jtxtEmpMobile1.setText(null);
        jtxtEmpAdd1.setText(null);
        jtxtEmpAdd2.setText(null);
        jtxtEmpZipCode1.setText(null);
        jtxtEmpEmail1.setText(null);
        jcomboxJobTitle.setSelectedIndex(-1);
        jtxtEmpSalary.setText(null);
    }//GEN-LAST:event_onReset1ActionPerformed

    private void jtxtEmpFirstName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmpFirstName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmpFirstName1ActionPerformed

    private void jtxtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstNameActionPerformed

    private void jcomRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomRoomTypeActionPerformed

    private void jButtonAddToEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddToEmpActionPerformed

String Receptionist= "$ 2000.00";
String RoomServiceManager="$ 3000.00";
String BookingManager="$ 5000.00";

if(jcomboxJobTitle.getSelectedIndex()==0){
    jtxtEmpSalary.setText(Receptionist);
}else if(jcomboxJobTitle.getSelectedIndex()==1){
    jtxtEmpSalary.setText(RoomServiceManager);
}else if(jcomboxJobTitle.getSelectedIndex()==2){
    jtxtEmpSalary.setText(BookingManager);
}
       
        
        
        //-----------------------\
        DefaultTableModel model= (DefaultTableModel) jTable2.getModel();
            model.addRow(new Object[]{
                jtxtEmpID1.getText(),
                jtxtEmpFirstName1.getText(),
                jtxtEmpLastName1.getText(),
                jtxtEmpEmail1.getText(),               
                jtxtEmpMobile1.getText(),
                jcomboxJobTitle.getSelectedItem(),
                jtxtEmpSalary.getText(),
            } );
    }//GEN-LAST:event_jButtonAddToEmpActionPerformed

    private void onDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onDelete1ActionPerformed

    private void onDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDelete2ActionPerformed
       DefaultTableModel model= (DefaultTableModel) jTable2.getModel();
        if(jTable2.getSelectedRow()==1){
            if(jTable2.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No data to delete", "Hotel Management System", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Please select a row to delete", "Hotel Management System", JOptionPane.OK_OPTION);
            }
        } else{
            model.removeRow(jTable2.getSelectedRow());
        }
    }//GEN-LAST:event_onDelete2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelSystem().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddToEmp;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExit1;
    private com.toedter.calendar.JDateChooser jDateBirthdate;
    private com.toedter.calendar.JDateChooser jDateCheckinDate;
    private com.toedter.calendar.JDateChooser jDateCheckoutDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox<String> jcomGender;
    private javax.swing.JComboBox<String> jcomGender1;
    private javax.swing.JComboBox<String> jcomRoomType;
    public javax.swing.JComboBox<String> jcomboxJobTitle;
    public javax.swing.JLabel jlblSalary;
    private javax.swing.JTextField jtxtAdd1;
    private javax.swing.JTextField jtxtAdd2;
    private javax.swing.JTextField jtxtCustID;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtEmpAdd1;
    private javax.swing.JTextField jtxtEmpAdd2;
    private javax.swing.JTextField jtxtEmpEmail1;
    private javax.swing.JTextField jtxtEmpFirstName1;
    private javax.swing.JTextField jtxtEmpID1;
    private javax.swing.JTextField jtxtEmpLastName1;
    private javax.swing.JTextField jtxtEmpMobile1;
    private javax.swing.JTextField jtxtEmpSalary;
    private javax.swing.JTextField jtxtEmpZipCode1;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtMobile;
    private javax.swing.JTextField jtxtRoomNo;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTaxAmt;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtZipCode;
    private javax.swing.JButton onDUpdate;
    private javax.swing.JButton onDelete;
    private javax.swing.JButton onDelete1;
    private javax.swing.JButton onDelete2;
    private javax.swing.JButton onReset;
    private javax.swing.JButton onReset1;
    private javax.swing.JButton onTotal;
    // End of variables declaration//GEN-END:variables
}
